### ISSUE TITLE
Bowtie 2 error - ATACseq

### ISSUE THREAD

**Issue by Rohi-Taitou** [zhaoshuoxp/Pipelines-Wrappers#1]
it seems as if the bowtie2 genome is not loaded 
thanks for sharing !

![image](https://github.com/user-attachments/assets/f7b9c940-a8bf-43e2-9d4a-beeb81b137b9)

**Comment by zhaoshuoxp** [comment]
> it seems as if the bowtie2 genome is not loaded thanks for sharing !
> 
> ![image](https://private-user-images.githubusercontent.com/89741012/358908828-f7b9c940-a8bf-43e2-9d4a-beeb81b137b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwOTgxOTcsIm5iZiI6MTcyNDA5Nzg5NywicGF0aCI6Ii84OTc0MTAxMi8zNTg5MDg4MjgtZjdiOWM5NDAtYThiZi00M2UyLTlkNGEtYmVlYjgxYjEzN2I5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDIwMDQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllNGE3YjM4NjI5OTdmMmFhZWM1Yzk2ZmIwOTNmMDQwMDViMTEyMDcxNzFjMWM1Y2E1ZDk3MmYxMTNkNzYwM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YWadq3mx3g52lLcyoJQLytS7C-J8w53Ep4-P6u8h9GY)

Hi ironbulb,  the hardcoded path of bowtie2 indexes is only for our servers, you have to either provide your own indexes with -x and -b (see help message) or edit the lines20-37 to the path on your server.  You can download the index files here:https://bowtie-bio.sourceforge.net/bowtie2/manual.shtml

**Comment by Rohi-Taitou** [comment]
I appreciate your response, and sorry for my mistake.
Assuming I don't use chromap, I will need to add both BT2 index and blacklist files ?

(It's a group of immune cells)

**Comment by zhaoshuoxp** [comment]
> I appreciate your response, and sorry for my mistake. Assuming I don't use chromap, I will need to add both BT2 index and blacklist files ?
> 
> (It's a group of immune cells)

yes you will need Bowtie2 index for aligning and blacklist for filtering the peaks after peak calling
